### PR TITLE
Enable in fullscreen 316

### PR DESCRIPTION
**Pull request by dmarrazzo**
Hi, please add this feature!
Thank you

### CODE REVIEW

**Comment by micheleg** [comment]
Hi,

thanks for the suggestion and code. There is a little problem. When  windows are full-screen the dash visibility is not updated. This has to be solved before merging. Temporary adding an visibility update when windows are in fullscreen - there might be a signal to connect to somewhere - should be enough.

**Comment by micheleg** [comment]
It should work ok now, can you test it?

**Comment by micheleg** [comment]
I  decided to disable this behaviour by default and added an option in the intellihide setttings. Almost ready to merge.

**Comment by dmarrazzo** [comment]
Ok great news! Thank you

**Comment by micheleg** [comment]
Merged in master [63c6f9f17], 3.16 [92d8728]  and 3.14 [e034700] branches.

**Pull request closed without merging**
