### PR TITLE
added white stroke to windows counter indicator dots

### PR DESCRIPTION
**Pull request by user501254**
See: https://github.com/micheleg/dash-to-dock/issues/170

### CODE REVIEW

**Comment by user501254** [comment]
Note:
I wasn't very sure about what to do with `dots.svg` since it didn't have other counterparts (bottom,rtl,top) so I left it unmodified.

**Comment by micheleg** [comment]
Those svgs are generated from the ```dots.svg``` with the ```make generate_dots_svgs ``` , which opens inkscape and rotates the dots.

**Comment by user501254** [comment]
Alright, will modify and add.

**Comment by user501254** [comment]
That should do it.

**Comment by micheleg** [comment]
Thanks, I'll test it for a while. It doesn't look too nice with the default theme, although it definitely increase the contrast of the dots.

**Comment by user501254** [comment]
You are welcome.
I tried some other color combinations and for now, fill color 2e3436 & stroke color ffffff seems to be working best, both belong to the default theme's color scheme.

**Comment by user501254** [comment]
Closing since it's no longer useful. See branch [rework_running_indicators](https://github.com/micheleg/dash-to-dock/tree/rework_running_indicators), https://github.com/micheleg/dash-to-dock/issues/170  & https://github.com/micheleg/dash-to-dock/issues/232

**Pull request closed without merging**
