### PR TITLE
theming: explicitly update solid style on showing the overview

### PR DESCRIPTION
**Pull request by beidl**
Properly update top bar and dock styling with maximized windows in the overview when transparency-mode set is set to ADAPTIVE

### CODE REVIEW

**Comment by beidl** [comment]
Guess I have to explicitly mark a few Ubuntu guys? @didrocks

**Comment by beidl** [comment]
"s/mark/tag/g" rather, don't want to give you the wrong idea :)

**Comment by didrocks** [comment]
Hey! Sorry for not being reponsive earlier on (I was off).
Is this change in https://github.com/micheleg/dash-to-dock/commits/master? We only do regular rebase and not add features that aren't in dashtodock itself. I can't find a corresponding commit there. (And so, no need to then do a separate/duplicated PR).

**Comment by beidl** [comment]
Created new pull request #706 as I'm not actively using Ubuntu with the Ubuntu session at the moment.

**Pull request closed without merging**
