### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Piterden**

### CODE REVIEW

**Comment by micheleg** [comment]
Hi Denis, why do you think the git/ssh address is better than the https one?

**Comment by Piterden** [comment]
Cause of with https the certificate doesn't work and you would need to enter login/pass each time.

**Comment by micheleg** [comment]
Yes, I agree with that, but:

* That only applies to the case you are pushing to the repository. Users have no write permission, so they never have to write a password anyway. 
* Even if that was not the case, I would assume anybody having set up an ssh certificate would find out by himself about that option. 

From a quick search online, the main argument pro https seem to be:
* Avoiding potential firewall issues

**Comment by Piterden** [comment]
But I had pushed, exactly)))

**Comment by 3v1n0** [comment]
There's no point for this.

**Pull request closed without merging**
