### PR TITLE
fix: empty space in panel mode

### PR DESCRIPTION
**Pull request by muhajirmuhajir**
this pull request will fix the issue [#1411 ](https://github.com/micheleg/dash-to-dock/issues/1411)
Screenshot-2021-04-11-07:30:14

### CODE REVIEW

**Review by 6uzm4n — APPROVED** [review]

**Comment by muhajirmuhajir** [comment]
Hi, this pull req has been so long waiting for any responses, Is there any other problem that needs to be solved?

**Comment by huf0813** [comment]
I also waiting for this PR to be merged, this PR would really help me to beautify.

@micheleg

**Comment by 3v1n0** [comment]
This doesn't apply anymore, and code changed a lot, is the issue still present?

**Comment by 3v1n0** [comment]
I feel this is fixed in current code, so in case feel free to open a new PR.

**Pull request closed without merging**
