### PR TITLE
Implementation to set the dash background color.

### PR DESCRIPTION
**Pull request by franglais125**
This adds the ability to set the background color for the dash from the
settings.

Issue reference: https://github.com/micheleg/dash-to-dock/issues/313

### CODE REVIEW

**Comment by franglais125** [comment]
screenshot from 2016-05-22 14-42-42

I made it compatible with the opacity setting, so one can independently use both of them.

**Comment by micheleg** [comment]
Hi,

thank you for your pull request. It seems to work very well and it is not invasive neither from the code  nor from the ui point of view. I would made just a change, moving the background color settings ui before the opacity one. After that, I'm ready to merge it. 

Would you mind rebasing the pull request to current master and updating the settings ui?

Thank you,
Michele

**Comment by franglais125** [comment]
Hi Michele,

Thanks for looking into this patch. I rebased and now the branches are now compatible.

I moved the option for the color above the opacity one, as requested!

I know it's a bit off-topic here, but while we are at it... Do you want me to open a PR for the Workspace isolation issue?
I have actually prepared three branches for that, in case you want to backport to Gnome 3.14 and 3.16.

Regards

screenshot from 2016-05-27 18-42-29

**Comment by franglais125** [comment]
Oops, looking at the previous screenshot I realized the switches didn't have an even spacing. Patch b2b3eef562a22969201466334811c032ee4ba361 takes care of that!

screenshot from 2016-05-27 18-47-25

**Comment by micheleg** [comment]
Merged [7db860c326567b4d7d17dc3c3fc655543e84e61b]. Thank you.

**Pull request closed without merging**
