### PR TITLE
appIcons: Add support for translating plural forms

### PR DESCRIPTION
**Pull request by 3v1n0**
Closes: #2100

### CODE REVIEW

**Comment by xalt7x** [comment]
Thanks for the quick response.

Unfortunately it still doesn't work for me
1. `make potfile` still generates po/dashtodock.pot without plural forms

> msgid "Quit %d Window"
> msgid_plural "Quit %d Windows"

However translation still works

2. I 've tried replacing
 ```
this._quitMenuItem.label.set_text(N__(
```
with
 ```
this._quitMenuItem.label.set_text(ngettext(
```
Now plural strings gets generated for po/dashtodock.pot

> msgid "Quit %d Window"
> msgid_plural "Quit %d Windows"
> msgstr[0] ""
> msgstr[1] ""

But after the actual build translation isn't used (strings remain in English)

**Comment by xalt7x** [comment]
Please review my PR to your branch which resolves the aforementioned issues.

**Comment by 3v1n0** [comment]
Done your merge, let me know if this should go in now.

**Comment by xalt7x** [comment]
Works for me, thanks!
dash-to-dock--plural

**Pull request merged**
