### PR TITLE
Add cycle through windows feature

### PR DESCRIPTION
**Pull request by gabrielmoreira**
Issue #183 

Added a new setting "Scroll action", with 3 options:
- Do nothing
- Cycle through windows
- Switch workspace

[screenshot](https://s29.postimg.org/pp1rhlu7r/Captura_de_tela_de_2017_01_08_00_43_54.png)

### CODE REVIEW

**Comment by micheleg** [comment]
Sorry for the late reply and thanks for your contribution. It seems to be working very well, and it totally makes sense to have this option. The settings look clear too.

I'll try to merge it as soon as possible, just let me review your code. I quickly skimmed through your changes. I have a concern about the changes in the setttings.ui file. By changing the file, it got updated to latest gtk version which might be a problem. At the moment the master version is meant for Gnome Shell 3.18-3.22. I'd ask you to isolate the changes related to the additional settings ui. I'll have to update the ui file sooner or later, but I prefer not to risk to break back-compatibility now.

**Comment by gabrielmoreira** [comment]
Hi @micheleg ! I returned the Settings.ui to the previous version, and applied only the difference.

I have no idea if this feature is well-programmed. This was my first contact with gnome-extensions, and for me it was not easy. I could not find good documentation, complete examples, and it is not quick to understand the various concepts. The biggest difficulty was to test. My gnome-shell froze several times when there was a bug. But I was determined to replace the plank, so I struggled a little bit more :)

Since I sent the patch, I have used it on my home computer and my work (Manjaro - archlinux), replacing Plank, and I had no problem.

In the future, I think we can put a feature similar to the shift + click action, we could have the shift + scroll action for a second action.

Anyway, grateful for the attention.

**Comment by micheleg** [comment]
There's no real documentation for extension development, and it doesn't help that it's often a fight to patch the upstream code, which can  makes some parts of the code awful.

Your implementation follows very much my code and look clean enough for merging. I'd like to rethink how this "optional feature" are organized but that will be for the future.

I've only changed the deadtime to 250 ms instead of 150 ms for consistency with the workspace scrolling (any thoughts on which is the optimal value?). The updated branch is here: https://github.com/micheleg/dash-to-dock/tree/scroll_cycle_windows.

I should merge the feature soon.

**Comment by gabrielmoreira** [comment]
I do not know what timeout would be the best setting for deadtime, but if it's easy and few lines of code, I suggest making this value configurable by gsettings (without ui, just gsettings). 

Thanks again.

**Comment by micheleg** [comment]
Merged in master [0040c2af8a76], Thank you!

**Comment by micheleg** [comment]
I only now remembered about the incompatibility with the "fixed icon size" option. At the moment the feature conflict with the ability to scroll to show the additional launchers.

**Pull request closed without merging**
