### PR TITLE
theming: Add support for Cogl.Color since Clutter.Color is deprecated in 47

### PR DESCRIPTION
**Pull request by vanvugt**
Closes: https://github.com/micheleg/dash-to-dock/issues/2284

### CODE REVIEW

**Comment by ZimbiX** [comment]
I just updated to Gnome 47 on Arch Linux, and to get background colour working again, had to install this extension from master to get this fix for https://github.com/micheleg/dash-to-dock/issues/2284. Probably best to do a release :pray: Thanks for the fix and maintaining this!

```bash
git clone git@github.com:micheleg/dash-to-dock.git
cd dash-to-dock
sudo pacman -S dart-sass
SASS=dart make install
```

**Comment by Mistakesos** [comment]
> I just updated to Gnome 47 on Arch Linux, and to get background colour working again, had to install this extension from master to get this fix for #2284. Probably best to do a release 🙏 Thanks for the fix and maintaining this!
> 
> ```shell
> git clone git@github.com:micheleg/dash-to-dock.git
> cd dash-to-dock
> sudo pacman -S dart-sass
> SASS=dart make install
> ```

I tested it, the background theme of dock works, but indicator "theme" still doesn't work. Did you also experience the same situation？What I mean is the small dot under the icon. If it's default, it will be displayed "on" the icon, but if it's customized, it will completely disappear ( Maybe not, just because the color is the same as the icon, it looks "disappeared" ) .

In short, if there is progress, it would be great. Thank to your commit !

**Comment by vanvugt** [comment]
@Mistakesos, the indicator dot issue is https://github.com/micheleg/dash-to-dock/issues/2222 and there are more colour fixes coming in https://github.com/micheleg/dash-to-dock/pull/2287

**Comment by Mistakesos** [comment]
> @Mistakesos, the indicator dot issue is #2222 and there are more colour fixes coming in #2287

After posting that comment, I started "watching" this project and saw your progress. It's really organized and fast. Today, I noticed that the master branch merged with a fix for custom colors(#2287), so I fetched the master branch and pulled it to the latest content. Now it works perfectly. Sincerely thank you!

**Pull request merged**
