### PR TITLE
Fix stylesheet for gnome 42

### PR DESCRIPTION
**Pull request by daniruiz**
With the update to gnome 42 the new updated branch ubuntu-dock works great but the stylesheet didn't get completely updated. Some of the spacings and margings look odd. This patch fixes it 

### Old:
Captura desde 2022-04-21 10-40-23
### New:
image

### CODE REVIEW

**Comment by daniruiz** [comment]
It's also the patch I created for the dash-to-dock extension for Kali Linux. Here is the source
https://gitlab.com/kalilinux/packages/gnome-shell-extension-dashtodock/-/blob/kali/master/debian/patches/fix-stylesheet-for-gnome-42.patch

**Review by Zorono — APPROVED** [review]

**Comment by proninyaroslav** [comment]
@daniruiz 
What could be the reason? I removed the old extension (for GNOME 41) and installed this.

**Comment by proninyaroslav** [comment]
This seems to be a problem with f36 itself, I see the same problem in the desktop extension.

**Comment by 3v1n0** [comment]
Some of this stuff was included in #1826 and #1827, so I'm closing this.

Please, make a new one in case there's something we missed.

**Pull request closed without merging**
