### PR TITLE
Click to show dock when window maximized

### PR DESCRIPTION
**Pull request by gogi983**
Hi, 
Is there any possibility to add an option like in "Workspaces-to-Dock" extension, which requires, if enabled, to click over the area where the Dock should appear if a window is maximized?

I imagine that it shouldn't be so hard to implement, but I have no skills in programming to do it or suggest some code to do it.

Regards.

### CODE REVIEW

**Comment by micheleg** [comment]
@gogi983 I guess the pull request was not intended? 

Would you mind pointing out at the option in workspace-to-dock to enable your desired behaviour? I quite don't understand what you are proposing.

**Comment by gogi983** [comment]
Oh sorry no it wasn't intended, my bad... Instead of opening a new thread in "issues", even it is more a suggestion/request than an issue, I probably clicked on "pull request", sorry...

Well there is an option in "Workspaces-to-dock" which, when checked, requires mouse click (in addition to hovering) to show dock when focused window is maximized.
Can you implement same stuff in your extension, I guess it's possible and would be really helpful if you could do this?

**Comment by micheleg** [comment]
Thanks, now I understand. I haven't looked at the implementation. I'm a bit concerned about having this as a default, because it might interfere with the user trying to click on some button of the application. It could be an option, but what is exactly the problem this feature solves?

**Comment by gogi983** [comment]
I didn't mean having it as a default but as a possible option one could enable by checking it. 
About your concern, I don't know exactly how they implemented it but there must be some tweakable stuff to do in the code part for this, as in "Workspaces-to-dock" extension one have to move mouse pointer really on the edge screen and click to make it appear so the area for click should be very very thin, about  1 or 2px... 

It solves nothing but I really appreciate the behaviour when a focused window is maximized as it prevents the extension to appear when I "accidentally" move the mouse too fast, and so only appears when I voluntarily click on the edge of the part of the screen where it is configured to appear.

**Comment by micheleg** [comment]
I see. Are you aware that you can disable intellihide with fullscreen applications? Would you mind opening an issue, so that I can close this pull request?

**Comment by gogi983** [comment]
I opened an issue so you can close the pull.

**Comment by micheleg** [comment]
Thanks.

**Pull request closed without merging**
