### PR TITLE
Gnome 3.36 support

### PR DESCRIPTION
**Pull request by 3v1n0**
Add code to make the extension to work on gnome-3.36 as per the upstream changes.

Again, keeping compatibility with 3.34, while technically possible, makes things way harder to maintain.

### CODE REVIEW

**Comment by Titaniumtown** [comment]
It compiles and runs fine for me

**Comment by mikedep333** [comment]
FYI: I released a dash-to-dock update for Fedora 32 (which is not in beta until Mar 17) with this PR applied against the master branch (5658b5c2217ab3b7a036d51b62b357ea99e8fedc):
https://bodhi.fedoraproject.org/updates/FEDORA-2020-f4ab471f85

[A user reported](https://bugzilla.redhat.com/show_bug.cgi?id=1794889#c5) (with screenshots) that while it does start successfully (thank you!), he has 2 regressions vs on Fedora 31 with GNOME 3.34 & v67 of dash-to-dock:

> (a) By default it is the exact same size and appearance as when you hit "Activities", traditionally by default it has been smaller to better suit large monitors.
> (b) The settings dialog boxes won't launch, so you cannot adjust the appearance and behavior.  I think many people make it even smaller than the default by tweaking it.

**Comment by 3v1n0** [comment]
> (a) By default it is the exact same size and appearance as when you hit "Activities", traditionally by default it has been smaller to better suit large monitors.

Thanks, this has been fixed by commit 367d382

**Comment by roombobcat** [comment]
@3v1n0 i'm using the latest commit and i'm still having alignment issues.
Screenshot from 2020-02-27 12-51-06

tried playing with dconf editor to see if i can get it to stick in the center, no dice.

**Comment by 3v1n0** [comment]
@roombobcat that's now fixed too... Before I was mentioning only the other issue.

Given I normally use it in extended mode I didn't notice such problems.

**Comment by roombobcat** [comment]
@3v1n0 just loaded it up and it works!

also tweaked the dconf settings and got it out of the compact mode too, good as it was before now.:)

**Comment by mikedep333** [comment]
> > (a) By default it is the exact same size and appearance as when you hit "Activities", traditionally by default it has been smaller to better suit large monitors.
> 
> Thanks, this has been fixed by commit [8bb16f4](https://github.com/micheleg/dash-to-dock/commit/8bb16f4712ff7dac34b9f5f9be4651f82bc9bfc6)

Thank you, I released a new Fedora 32 update with it:
https://bodhi.fedoraproject.org/updates/FEDORA-2020-58f0e9ce86

**Comment by ColinKinloch** [comment]
Workspace switching via scrolling is broken as `Utils.DisplayWrapper` doesn't seem to exist.

I got it working by switching `Utils.DisplayWrapper.getWorkspaceManager` in `docking.js` with the implementation from [gnome-shell-wsmatrix](https://github.com/mzur/gnome-shell-wsmatrix/blob/47ae1592478179d7dfd932dc826fa5ed8f6d7170/wsmatrix%40martin.zurowietz.de/DisplayWrapper.js#L9-L11):

```js
function getWorkspaceManager() {
  return global.screen || global.workspace_manager;
}
```

**Comment by micheleg** [comment]
@3v1n0 Thanks a lot for the pull request! I just had a quick look through the changes and everything seems sinsible. Totally fine to only target 3.36. Will have a more detaild look this week.

**Comment by timocapa** [comment]
There seems to be an empty space to the right for me on Arch.

Gnome 3.35.92.

image

**Comment by roombobcat** [comment]
> There seems to be an empty space to the right for me on Arch. The notification count seems too small too.
> 
> Gnome 3.35.92.
> 
> image
> 
> E: "Show Applications" animation comes and goes from / to the top left instead of the dock.

can also confirm i'm also having this issue.

**Comment by 3v1n0** [comment]
> Workspace switching via scrolling is broken as `Utils.DisplayWrapper` doesn't seem to exist.
> 
> I got it working by switching `Utils.DisplayWrapper.getWorkspaceManager` in `docking.js` with the implementation from [gnome-shell-wsmatrix](https://github.com/mzur/gnome-shell-wsmatrix/blob/47ae1592478179d7dfd932dc826fa5ed8f6d7170/wsmatrix%40martin.zurowietz.de/DisplayWrapper.js#L9-L11):
> 
> ```js
> function getWorkspaceManager() {
>   return global.screen || global.workspace_manager;
> }
> ```

Mh, this looks more due to commit 1334ab3fbadca0c91adac9d4059c36233de4f28d, so I should fix that instead in master.

Thanks for pointing it out though

**Comment by 3v1n0** [comment]
> There seems to be an empty space to the right for me on Arch. The notification count seems too small too.
> 
> Gnome 3.35.92.
> 
> image
> 
> E: "Show Applications" animation comes and goes from / to the top left instead of the dock.

I've looked into this issue a bit deeply, but this is caused by [upstream commit 4f8e518d42e4f07239a41fc3cef9515b94c59dda](https://gitlab.gnome.org/GNOME/mutter/merge_requests/1070), so looking into that now

**Comment by jnsh** [comment]
> (b) The settings dialog boxes won't launch, so you cannot adjust the appearance and behavior. I think many people make it even smaller than the default by tweaking it.

The setting dialog works for me, if you open it via `gnome-shell-extension-prefs` or `gnome-tweaks`. However, the popover that appeared when you right-clicked the 'Show Applications' button, that could be used to open the settings, doesn't appear on 3.36. I'm wondering whether this is what the quoted report meant.

I can also reproduce the 'show applications' animation issue, and the invalid width/padding issue, that @timocapa mentioned few comments up. The latter issue is even worse if you're using left/right position, as it hides large number of the icons ([screenshot](https://user-images.githubusercontent.com/39574454/75776555-dfb86700-5d5c-11ea-920b-8ae10c79ab2d.png)).

The screenshot is using 100% dock size limit, so something seems to be wrong with the dock size calculation. If the dock is placed on bottom, with 100% size limit, the dock spans trough the whole screen width, though the 'padding' seems to remain regardless of the size limit: ([screenshot with 100% size limit](https://user-images.githubusercontent.com/39574454/75777338-7afe0c00-5d5e-11ea-8963-98c9438297f4.png))
([screenshot with 33% size limit](https://user-images.githubusercontent.com/39574454/75777339-7cc7cf80-5d5e-11ea-934b-4288d3237d04.png)).

Everything else seems to work as expected.

**Comment by mikedep333** [comment]
I released another Fedora 32 update with the several new commits added 5 days ago:
https://bodhi.fedoraproject.org/updates/FEDORA-2020-633701de74

**Comment by ColinKinloch** [comment]
I just updated my fedora 32 install, the settings dialogue now works and the icons are no longer small.

The dash is correctly centred in the left of my display, however the icons seem to be pushed beyond the dash extents (I rotated the screen shot to avoid taking too much vertical space):
Screenshot_Gnome_3 35 91_2020-03-03


`journalctl  /usr/bin/gnome-shell -f -o cat` prints the following, with the final line repeated several times:
```
JS ERROR: (null)
JS ERROR: InternalError: too much recursion
vfunc_get_preferred_height@/home/user/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/docking.js:144:49
```

Which references docking.js line 144, in [my case](https://github.com/micheleg/dash-to-dock/pull/1097#issuecomment-593151829):
```
 140     /**
 141      * Just the child height but taking into account the slided out part
 142      */
 143     vfunc_get_preferred_height(forWidth) {
 144         let [minHeight, natHeight] = this.child.get_preferred_height(forWidth);
 145         if ((this.side ==  St.Side.TOP) || (this.side ==  St.Side.BOTTOM)) {
 146             minHeight = (minHeight - this._slideoutSize) * this._slidex + this._slideoutSize;
 147             natHeight = (natHeight - this._slideoutSize) * this._slidex + this._slideoutSize;
 148         }
 149         return [minHeight, natHeight];
 150     }
```

Perhaps this `DashSlideContainer` contains itself?

**Comment by timocapa** [comment]
I get the same thing, but for forHeight instead

```
JS ERROR: (null)
vfunc_get_preferred_width@/home/timo/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/docking.js:128:36
vfunc_get_preferred_width@/home/timo/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/docking.js:128:47
```

```
    /**
     * Just the child width but taking into account the slided out part
     */
    vfunc_get_preferred_width(forHeight) {
        let [minWidth, natWidth] = this.child.get_preferred_width(forHeight);
        if ((this.side ==  St.Side.LEFT) || (this.side == St.Side.RIGHT)) {
            minWidth = (minWidth - this._slideoutSize) * this._slidex + this._slideoutSize;
            natWidth = (natWidth - this._slideoutSize) * this._slidex + this._slideoutSize;
        }
        return [minWidth, natWidth];
    }
```

**Comment by micheleg** [comment]
I'm having huge problem with the dock icon sizing/positioning when not in extended mode. It's partially related to 66a17dc1aca9d606dfab376f5eb7b8d51eb880f9, de2baddaa5d66fb7a5137a03ce6975fa4c0eab19 although just undoing these commits is not enough to solve the problem. The sizeconstraint which feed the icon size machinery seem to be ignored depeneding on the alignement of the actor. Upstream changes?

The problem is not evident with the dock in exteded mode.

The whole machinery is quite complicated in order to obtain the correct mouse event tracking at least in the early gnome-shell versions. It is possible that some of these are not necessary anymore and that it could be greatly simplified. In the meantime, I tweaked the dock container alignemts in order to restore the corrent behaviour in the tmp/gnome-3-36 branch (65a20f7369d771af830a36 and  85fd4ff47ac37363acf038c03fbe5f25) which is built on top of this branch.

Any test and feedback on these pathches is very apprectiated.

**Comment by micheleg** [comment]
Also [7b421ced487a4045b1257b8a50076687f6cc0bd3] should fix the showapps animation

**Comment by timocapa** [comment]
Built both gnome-shell and mutter from `master`, latest commit of dash-to-dock is 032a52ec6042a0f974fc93054ba1c14e8424216f, though I'm not sure if that branch was supposed to fix that?

image

**Comment by micheleg** [comment]
@timocapa sorry, last commit was wrong. Try now (I reverted the commit while I fix it).

**Comment by timocapa** [comment]
Current HEAD **is** at the revert

**Comment by micheleg** [comment]
Hopefully [3db72e7e] fix for horizontal mode  too

**Comment by timocapa** [comment]
Size looks fine now, "Dock size limit" still moves the dock around at the bottom however. :)

image

**Comment by micheleg** [comment]
>"Dock size limit" still moves the dock around at the bottom however. :)

What do  you mean?

**Comment by timocapa** [comment]
https://i.imgur.com/D11kml3.mp4


> > "Dock size limit" still moves the dock around at the bottom however. :)
> 
> What do you mean?

**Comment by micheleg** [comment]
I don't seem to have that problem... weird

**Comment by jnsh** [comment]
I can reproduce the 'dock size limit moves the dock' issue as well. It happens for vertical panel also, where I was able to reproduce it even before https://github.com/micheleg/dash-to-dock/commit/3db72e7e8936f692c29c84c9fc5bf26a92a71061.

**Comment by TheAifam5** [comment]
I am sorry for out-of-context question but I love the theme of @roombobcat :D Can someone tell me what the name of the theme is?

**Comment by roombobcat** [comment]
> I am sorry for out-of-context question but I love the theme of @roombobcat :D Can someone tell me what the name of the theme is?

it's a modified version of Ant Dracula with blue highlights instead of purple/pink highlights. i also have a extension to enable slight transparency on the top bar as well.

**Comment by v4rakh** [comment]
Depending on the dock size limit icons disappear/will be moved up with empty space. It looks better when having this not left but bottom side, maybe because there's much more space.

lowest

100%_size_limit

**Comment by green4ao** [comment]
In my case dash-to-dock aligned to left corner
Screenshot from 2020-03-08 20-45-06

**Comment by green4ao** [comment]
> https://i.imgur.com/D11kml3.mp4 - Unless this is intended behavior, which I don't think it is?
> 
> > > "Dock size limit" still moves the dock around at the bottom however. :)
> > 
> > 
> > What do you mean?

Same here...

**Comment by jesusignazio** [comment]
> @3v1n0 i'm using the latest commit and i'm still having alignment issues.
> Screenshot from 2020-02-27 12-51-06
> 
> tried playing with dconf editor to see if i can get it to stick in the center, no dice.

Sorry for asking here, but what theme is that? I love it.

**Comment by AlexWayfer** [comment]
:grimacing: 

image

**Comment by ruabmbua** [comment]
Same problem here with the dock size limit. Layout is all messed up.

GNOME Shell 3.36.0 on ArchLinux.

**Comment by 3v1n0** [comment]
Ok, with the latest commits I think most of the visual issues I've been addressed.

However I'm still struggling with #1117

**Comment by jnsh** [comment]
Thanks for working on this.
Only thing I noticed with the latest revision, is that the icon rearranging is still broken.
Apart from that, all issues I've encountered so far seem to be fixed.

**Comment by marty-shields** [comment]
Is any help needed to get this PR over the line? I don't have any experience in developing these sort of things but I am a Node/.Net developer for the past 5 years

**Comment by AdsonCicilioti** [comment]
@roombobcat, what this theme?
Is beautiful!

**Comment by v4rakh** [comment]
> Ok, with the latest commits I think most of the visual issues I've been addressed.
> 
> However I'm still struggling with #1117

Your branch works fine for me, no glitches detected so far.

**Comment by x80486** [comment]
Indeed, with this last commit I don't see any errors and/or warnings in the `systemd` journal. I use the dock like Ubuntu: extended to the screen edges. I'm under Arch Linux: `Linux uplink 5.4.24-1-lts #1 SMP Thu, 05 Mar 2020 20:29:59 +0000 x86_64 GNU/Linux`.

**Comment by marty-shields** [comment]
Works for me as well for the most part. The only issue I am finding is with re arranging icons

**Comment by jnsh** [comment]
I just noticed another regression: It's not possible to click "trough" the transparent main dash-to-dock box, i.e. the area with red border in this screenshot:
Screenshot from 2020-03-14 17-10-53

In other words, you cant select/activate any windows by clicking them over that area, even though it appears fully transparent.

**Comment by xTeixeira** [comment]
I also have the same issues as the last two commenters. Can't rearrange icons and can't click through the area @jnsh pointed out in their screenshot.
Other than that the extension now works perfectly, so thanks for that.

**Comment by hrdwrrsk** [comment]
> Works for me as well for the most part. The only issue I am finding is with re arranging icons

Icon rearranging actually works if dock are moved to Left/Right side + extended mode, but not in bottom position. don't know why :\

**Comment by 3v1n0** [comment]
I've pushed another revision where at least I've fixed the infinite loop we may had...

I've also fixed locally the problem with the mouse non-pass-through, but unfortunately due to a GJS issue I can't just use the best fix for this here, so I need to study some workaround.
At least until gjs won't include this fix https://gitlab.gnome.org/GNOME/gjs/-/merge_requests/404

**Comment by jnsh** [comment]
Commit https://github.com/micheleg/dash-to-dock/pull/1097/commits/18a3cd220a0ec933f298d01bd3b3f0b7b8f7caf5 causes issues with the app-icon grid, when it's activated outside of the overview, either by clicking the 'Show applications' button on dash-to-dock, or by pressing Super-A: The overall app-grid size/alignment seems incorrect, and the [ Frequent | All ] buttons aren't visible.

[See this video](https://www.dropbox.com/sh/5jll4gcho0hjocu/AADmz4lO9qiGNPRAhBjPZ6Zea?dl=0&preview=Screencast+from+18-03-20+18%3A55%3A12.webm) for better description.

 This only seems to happen, if the dock is placed at the bottom of the screen.

**Comment by 3v1n0** [comment]
@jnsh thanks for the report, this is now fixed in latest version.

The spacer is replaced (and for real) only when we're in vertical mode.

**Comment by aliasbody** [comment]
I don't know if this is related, but on the latest commit I can't drag-drop the icons into another place of the bar.

**Comment by dukase** [comment]
> I don't know if this is related, but on the latest commit I can't drag-drop the icons into another place of the bar.

Happen to me on Ubuntu 20.04 only when icons on top/bottom of the screen. left
Workaround: switching to icons on the side, arrange them and switch back.

**Comment by jeaye** [comment]
Is this blocked on bugs, or just a review?

**Comment by dvorapa** [comment]
The icon menu still seems quite broken, at least its title:
Snímek z 2020-03-31 21-31-44
(Arch Linux, compiled yesterday from branch)

**Comment by jnsh** [comment]
@dvorapa That looks like your shell theme is broken, or not updated to 3.36. Try with the default theme.

**Comment by dvorapa** [comment]
> @dvorapa That looks like your shell theme is broken, or not updated to 3.36. Try with the default theme.

I'll try, but for closed apps it is correct 🤷‍♂️

**Comment by rmader** [comment]
One more thing to make opening the settings work again:

`Util.spawn(["gnome-shell-extension-prefs", Me.metadata.uuid]);` needs to be replaced by `ExtensionUtils.openPrefs();`

See also https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/1163 and https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/pull/203

**Comment by SSouper** [comment]
@rmader Tried, that, still cant get it to work :( running arch btw with gnome version 3.36.1

**Comment by rmader** [comment]
> @rmader Tried that, still cant get it to work :( running arch btw with gnome version 3.36.1

Yeah, unfortunately we only merged the new convenience API (`ExtensionUtils.openPrefs()`) two days ago - so it will only arrive in 3.36.2 :(

Maybe arch will issue a new build from git earlier though.

**Comment by mikedep333** [comment]
I released another update for Fedora 32, with the current set of patches (36) against master (70f1db83cf6a4e83c26e6ec8b89f9a8477905406)

https://bodhi.fedoraproject.org/updates/FEDORA-2020-63860763a4

**Comment by mikedep333** [comment]
I issued another update for Fedora 32, with the current set of patches (36, [pushed yesterday](https://github.com/micheleg/dash-to-dock/pull/1097#event-3216150535)) against master (77bc707)

https://bodhi.fedoraproject.org/updates/FEDORA-2020-63860763a4

**Comment by mikedep333** [comment]
@micheleg @3v1n0 These patches may not be perfect yet, but I ask you to please release a new version with them anyway by 4/21.

Arch & Debian Sid are already on 3.36. Fedora 32 is launching on 4/21 or 4/28. Ubuntu 20.04 on 4/23. Mixed/bad reviews are already being submitted:: https://extensions.gnome.org/extension/307/dash-to-dock/

(My co-maintained Fedora RPM only covers Fedora users that install from RPM, not from extensions.gnome.org . They'd have to uninstall from extensions.gnome.org and re-install from RPM.)

**Comment by sirusss** [comment]
> @3v1n0 i'm using the latest commit and i'm still having alignment issues.
> Screenshot from 2020-02-27 12-51-06
> 
> tried playing with dconf editor to see if i can get it to stick in the center, no dice.

Unrelated....what gtk theme is this?

**Comment by 3v1n0** [comment]
Ok I've spent some more time on this and now the DnD shoud work properly also in horizontal moe

**Comment by micheleg** [comment]
I finally managed to look into this. I did really had trouble getting a gnome-3.36 system working (and it seems while using the beta of ubuntu 20.04 for a while I was basing my debugging on an unfinished gnome-shell versions, which resulted in inconsistent behaviours as compared with other linux distributions). Just updated my VM and tested current branch. I'm happy to see all the fixes and cleanups by @3v1n0: amazing work!

It seems to me the outstanding issues are:
* icon reordering in horizontal mode
* the clickthrough issue as pointed out by @jnsh: https://gitlab.gnome.org/GNOME/gjs/-/merge_requests/404 that was mentioned as a stopping factor is now merged.

**Comment by mikedep333** [comment]
I released another Fedora update with these latest patches against master branch:
https://bodhi.fedoraproject.org/updates/FEDORA-2020-f20319eaa0

However, I have an issue I did not experience previously. With "Fixed icon size" disabled (by default) the "Icon size limit" is not respected. More specifically, it is only respected under 16; 16 seems to be the max size.

Screenshot from 2020-04-16 22-24-57

**Comment by jnsh** [comment]
> However, I have an issue I did not experience previously. With "Fixed icon size" disabled (by default) the "Icon size limit" is not respected. More specifically, it is only respected under 16; 16 seems to be the max size.

I didn't have this issue when I checked this PR yesterday. After rebuilding it just now, I can reproduce this, so it seems to be a very recent regression.

@micheleg The icon reordering issue was fixed in the latest revision, according to [this comment](https://github.com/micheleg/dash-to-dock/pull/1097#issuecomment-614423953) and confirmed by my own testing.

The click-trough issue seems to be the only remaining problem.

**Comment by lazyfrosch** [comment]
Thanks for your patches and work on this great extension.

The only thing I noticed is due to stacked monitors, since we replace the original dock in overview, the content content shrinks to a very small height. For both search and window overview.

This seems to only happen when there is a screen above the primary.

Does not happen with extension disabled.

Bildschirmfoto von 2020-04-17 09-14-17

Bildschirmfoto von 2020-04-17 09-14-27

**Comment by micheleg** [comment]
@jnsh which commits are meant to have fixed the icon orderinng and click through problem: I'm still experiencing the bugs on Ubuntu 20.04 with this branch.

**Comment by jnsh** [comment]
@micheleg I couldn't tell the exact commits, but I can't reproduce either issues any more on Arch with latest gnome-shell and mutter from `gnome-3-36` git branches.

Maybe @3v1n0 could confirm.

**Comment by micheleg** [comment]
I can confirm the click-through is fixed if I remove this condition https://github.com/micheleg/dash-to-dock/pull/1097/commits/2882d6bb7d4d31fe28006a6456f1d3e61ab8f617#diff-2744291973b5ff72589a6f2d30c4414bR164 in the code. I'm not sure if it is safe to do so. i stil can't drag icons horizontally  though.

**Comment by jnsh** [comment]
> I can confirm the click-through is fixed if I remove this condition https://github.com/micheleg/dash-to-dock/commit/2882d6bb7d4d31fe28006a6456f1d3e61ab8f617#diff-2744291973b5ff72589a6f2d30c4414bR164 in the code.

Arch is shipping `gjs-1.64.1`, so the condition should pass on my system. Looks like ubuntu 20.04 also [comes with the same gjs version](https://packages.ubuntu.com/focal/gjs), so it seems odd that it didn't work for you without removing the conditional.

**Comment by micheleg** [comment]
Ok, I was sonehoe using an outdated branch, and mine had a check on vesion `16501` instead of `16401`. No I see that both problems are solved.

I tried to reproduce @lazyfrosch problem with multimonitors and @mikedep333 with icon size.

**Comment by micheleg** [comment]
Correction, the icon size problem occurs but only in non panel mode.

**Comment by jnsh** [comment]
I can reproduce the multimonitor issue reported by @lazyfrosch, but only when dash to dock is in both panel mode and horizontal mode (position left or right).

**Comment by micheleg** [comment]
@jnsh yes, I can reproduce it now, thanks.

**Comment by micheleg** [comment]
I'm merging this and will look into solving the known regressions next.

**Comment by micheleg** [comment]
PR #1171 should hopefully soive th icon size problem without introducing further regressins.

**Comment by micheleg** [comment]
and #1172 should fix  the problem reported by @lazyfrosch.

**Comment by HugoLiconV** [comment]
> There seems to be an empty space to the right for me on Arch. The notification count seems too small too.
> 
> Gnome 3.35.92.
> 
> image
> 
> E: "Show Applications" animation comes and goes from / to the top left instead of the dock.

Not related to this issue but what theme are you using for the icons and the dock?

**Comment by AdsonCicilioti** [comment]
> Not related but does anyone know what theme are these?
> image
> image

Yep! Is nice! I also want knows!

**Comment by HugoLiconV** [comment]
@AdsonCicilioti This one is called [ant](https://www.gnome-look.org/p/1099856/) 
image

**Pull request merged**
