### PR TITLE
Fix intellihide conflict with desktop icons gnome shell extension

### PR DESCRIPTION
**Pull request by dr3mro**
Hello, 
I have reported this and managed to find a patch, Please I would appreciate accepting it into main branch.
Thank you. 
Amr

### CODE REVIEW

**Comment by smedir** [comment]
Hi,

This commit will not fix the problem, probably for the Gtk3 version of DING (Although I have not tried it with the Gtk3 version).

The better very specific solution may be- 

`
At the top of the function at line 322, in _handledwindow() -

const ignoreApps = [ 'com.rastersoft.ding',  'com.desktop.ding' ];
const wmClass = meta_win.get_wm_class();

else if (ignoreApps.includes(wmClass) && meta_win.is_skip_taskbar())
        return false;`

A more generic solution at the same level could simply be

`else if (meta_win.is_skip_taskbar())
       return false;`

Would have to be checked in X11, but I think it will work....

**Comment by dr3mro** [comment]
That's awesome 😍 but I can confirm my solution works with gnome 43 on fedora 37

**Comment by smedir** [comment]
Yes it will work perfectly for the Gtk4 DING! :smile:

**Comment by dr3mro** [comment]
Anyways, please do what ever necessary to fix it.
have a nice day 
👍

**Comment by dr3mro** [comment]
please accept pull request

**Comment by dr3mro** [comment]
I have updated the code please recheck and accept the pull request.

**Comment by smedir** [comment]
I tried this out, this will not work when case IntellihideMode.ALL_WINDOWS is considered in dodge windows. The dock will hide all the time.

I will submit a new pull request with the very specific fix I proposed earlier.

**Comment by 3v1n0** [comment]
Duplicate of #1890

**Pull request closed without merging**
