### PR TITLE
Signal when the dash (and top panel) transparency has changed.

### PR DESCRIPTION
**Pull request by passingthru67**
NOTE:
This will help workspaces-to-dock (and other extensions) to sync with the panel/dash transparency.

### CODE REVIEW

**Comment by micheleg** [comment]
Thanks for the pull request. I'm intentionate to support this. What is yout goal? Which specific transparency change are you trying to track? i'm asking because we are supporting different transparent behaviours and I'm not sure if these signals are enough.

**Comment by passingthru67** [comment]
This is mainly for the adaptive transparency (because it affects the top panel), but should also apply to the dynamic transparency. My goal is to provide dynamic/adaptive transparency for workspaces-to-dock that stays in sync with dash-to-dock and the top panel.

**Comment by micheleg** [comment]
Woudn't inside this https://github.com/micheleg/dash-to-dock/blob/master/theming.js#L437 be the right place to emit the signals, together with the setting of the two styles?

**Comment by passingthru67** [comment]
That's where I thought I had put it. Here's the three functions that I've added emit signals to. I'm pretty sure I synced with upstream changes before I made the mods.

enable .. emit 'transparency-enabled'
disable .. emit 'transparency-disabled'
_updateSolidStyle .. emit 'update-solid-style'

**Comment by micheleg** [comment]
Sorry, I got fooled by the code folding... so you just want a ''update-solid-style', without information on which status (solid/transparent) is set?

**Comment by passingthru67** [comment]
It would be nice to include that information in the emit signal if possible.

**Comment by micheleg** [comment]
some user_data could be added to the signal (this.emit('update-solid-style; true/false)), or two indepedent signals could be emitted. I would do the first.

**Comment by passingthru67** [comment]
That would be nice. Do you want me to rework the pull request with the changes?

**Comment by micheleg** [comment]
I would appreciate it :)

**Pull request closed without merging**
