### PR TITLE
Update de.po

### PR DESCRIPTION
**Pull request by prdiewelt**
I have inserted new translations and modified some old ones. May still be improved, also some strings are untranslatable (“Behaviour when clicking…”, “Cycle through windows”, “Webpage”).

### CODE REVIEW

**Comment by micheleg** [comment]
Thank you. Merged into master and gnome-3.14 branches. Can't you really express those concepts anyhow?

**Comment by prdiewelt** [comment]
The problem is that these strings are not in the .po-file and I don't know, how to add them…

**Comment by micheleg** [comment]
If you run make```make mergepo``` the po file should be updated with all newly added strings.

**Comment by prdiewelt** [comment]
Does it work like this? Webpage is still not found, but this is not so important…

**Comment by micheleg** [comment]
My fault, that string was not marked as translatable. It's fixed now in master. Any other string missing? If you send me the updated version I'll merge it.

**Comment by prdiewelt** [comment]
Now everything should be OK.

**Comment by micheleg** [comment]
Perfect. Merged.

**Pull request closed without merging**
