### PR TITLE
Minor optimization

### PR DESCRIPTION
**Pull request by zapashcanon**
Just a minor optimization.

Before the loop:  avoid one multiplication and two subtractions but add two additions.

`h - 2 * n * r - (n - 1) * s`
= `h - n * (2 * r + s) + s`

In the loop: avoid one multiplication.

`(2 * i + 1) * r + i * s`
= `i * (2 * r + s) + r`

### CODE REVIEW

**Comment by micheleg** [comment]
Thanks for the suggestion. Did you actually profile the code? I understand that in principle it could be faster, but is it actually the case?

**Comment by zapashcanon** [comment]
No I didn't, I'm not very into javascript and have no idea how to do this.

But as it's an interpreted language, I think it's more likely to be the case.

**Comment by micheleg** [comment]
I'm not an expert by any means, I'm not sure whoat the jit compiler does. I quickly try to run  throgh gjs these snippets:

```
let h = 12.0
let n=3
let r = 2.0
let s = 2
let result;
for (let i=0; i<10000000; i++) {
	result = h - n * (2 * r + s) + s;
} 
```
and this:
```
for (let i=0; i<10000000; i++) {
	result = h - 2 * n * r - (n - 1) * s;
} 
```
and I can't see any noticeable difference. Not a very scientific measurement, I agree.

**Comment by zapashcanon** [comment]
I think it's because it's the wrong expression. ;)

`result` doesn't depends on `i` here. So, `result` always has the same value. I guess the compiler is smart enough to notice it and computes it before.

But even with the right expression, it wouldn't be easy to test, as giving predefined values to `r` and `s` would allow the compiler to compute part of the result before execution.

**Comment by micheleg** [comment]
Yes, I actually included the ```i``` in the expression in my test but couldn't see any difference either. I'm still to my point that if you can't profile it (or are sure it's faster) it's not an optimization.

**Comment by zapashcanon** [comment]
Yep' I understand. Will try to have a look at how to check if there's a difference, could be interesting. But probably won't find the time soon.

**Comment by zapashcanon** [comment]
Just tried [this](https://godbolt.org/g/XDDXEW). Looks like gcc isn't smart enough to simplify it with `-O2` (the default). In this case, it's clear that there's an optimization. I also tried with `-O6`, assembler code produced is better too. :)

So, I'm not sure, but I think that if gcc isn't smart enough to simplify it, then jit - or whatever is used in gnome - isn't.

**Pull request closed without merging**
