### PR TITLE
RFC: Trash and Removable Device Icons

### PR DESCRIPTION
**Pull request by philipl**
This set of changes adds Trash and Removable Device/Drive icons similar to what the Unity dock offers. 

I don't consider it a complete change at this point; I think the code organisation isn't correct, if nothing else, but I'm particularly interested in feedback on the way I created the icons using DesktopAppInfo.

Other obvious shortcomings:
- Lack of Translations
- Nautilus dependency in Empty Trash call
- No drag-and-drop for Trash (I don't personally care about this)
- 'Inauthentic' placement of Trash Icon

dash

### CODE REVIEW

**Comment by franglais125** [comment]
I'd love to have this! It seems non-trivial ti implement though, and not having d-n-d is too bad (although nothing we can do about it).

Quick comments:
1. Clicking on the icon is supposed to open the location? This is not working for me now. WIP?
2. On Debian, external USB drives don't seem to have the correct icon:

screenshot from 2017-10-08 13-42-51

Cheers!

**Comment by philipl** [comment]
My handling of the icon is too simple. It's a themed icon and so has multiple names, and the name that actually yields an icon varies depending on theme, and indirectly that depends on the distro.

I would need to iterate over the names and pick the first one that actually works.

**Comment by philipl** [comment]
I've updated the pr with icon lookup; please try it out.

**Comment by franglais125** [comment]
Nice and quick fix! It's showing the correct icon now, at least for this drive I just tested.

**Comment by philipl** [comment]
Another known problem is that opening a removable drive location creates a window that's mapped to Nautilus in the dock - so if you click on it again, you get a new window each time.

Unity had this exact problem initially as well, so the Canonical folks patched in a dbus mechanism to get a mapping of XIDs to file locations which they used to recognise removable drive windows.

The original bug report is here: https://bugs.launchpad.net/unity/+bug/887449

and there's a patch in the ubuntu sources for Nautilus.

The next step on my side is to work out the best west to override the window -> app mappings that the shell is doing.

**Comment by philipl** [comment]
Just pushed an incremental update to implement Unity's window mapping for the special icons.

**Comment by philipl** [comment]
I've done some refactoring so that all the new logic is properly contained. I feel good about the code organisation now.

**Comment by philipl** [comment]
Adding translation support.

@micheleg: I consider this mergeable now, if you're interested in looking.

**Comment by franglais125** [comment]
Thanks a lot for the continuous work on this! I've been using it since last time with great success (and some minor quirks).

I tested today the latest code from your branch, but I can't get the extension to load properly. Upon logging in, the shell freezes for ~10 seconds, and then loads with the extension disabled and this error in the log:

```
Oct 13 16:10:38 v131 gnome-shell[14761]: Extension "dash-to-dock@micxgx.gmail.com" had error: Gio.IOErrorEnum: Error calling  StartServiceByName for org.freedesktop.FileManager1: Timeout was reached
```

This is on Gnome 3.26, Wayland.

**Comment by philipl** [comment]
Thanks for the feedback.

The special window matching logic that Ubuntu patches into nautilus is X11 specific as it identifies windows by XID. I have no idea what happens in Wayland and cannot easily test yet as my primary machine uses nvidia graphics. I'll be able to try it out in a couple of weeks when I can upgrade another machine to 17.10. I had hoped that it would just fail to report windows and wouldn't do something nasty like timeout.

But one thing - if you log out and back in again, does it still block for 10 seconds? I had a problem where it would get stuck like this and I had to log out to fully restart gnome shell.

**Comment by philipl** [comment]
Pushed a few improvements including what should be a fix for freezing if the DBus proxy decided to be slow to init.

**Comment by micheleg** [comment]
I tried to run the code on 3.22, but it is not compatible due to the use of the operator ```...```. I want  to maintain compatibility with older versions for the moment, so these javascript features should not be used.

**Comment by philipl** [comment]
I've updated it to use push.apply() syntax. Should work now.

**Comment by micheleg** [comment]
```Map.forEach``` is also not supported unfortunately.  The supported syntax is  ```for (let [k,v] of Map){ }```.  So is ```Array.from()```. It's annoying not being able to use these, but I prioritize back compatibility. 

Anyhow, I got the branch running.

**Comment by philipl** [comment]
New update. I've fixed the js compatibility issues you mentioned, and added an improvement to deduplicate when a window is listed twice due to a location being open in multiple tabs.

**Comment by philipl** [comment]
I had a chance to test in Wayland. As expected, window tracking doesn’t work, but it fails gracefully. It looks like the Nautilus patch would need enhancements.

@micheleg, are you interested in merging this? Is there anything you’d like me to address?

**Comment by didrocks** [comment]
@franglais125: On drag and drop, we had "virtual placeholder" in unity if  you are interested. Basically, the default of the gsettings key was:
[<list of favorites app>, 'unity://running-apps',  'unity://expo-icon', 'unity://devices']

The running apps were the additional applications running but not in favorites, expo-icon, was the workspace expo mode (doesn't have any equivalent in GNOME Shell) and devices were those mounted and unmounted removable devices with an option to mount/unmount/unplug them.

So, moving one item was moving the whole group. I don't say that's what you want to do here, just giving a possible solution we explored on Unity some years ago ;)

**Comment by 0matgal0** [comment]
Works okaish. I have a 2 issues:
- the trash / removable icons are not movable (even though it might seem like they can be moved)
- opening trash actually opens nautilus not trash itself (as you can see the trash icon is not highlighted):
image

I know that unity had some issues with decoupling nautilus with device icons but afaik they somehow figured it out in 16.04 or something like that.

**Comment by philipl** [comment]
@0matgal0. I'm guessing you're using Wayland. As I said above, window matching doesn't work on Wayland.

**Comment by philipl** [comment]
I've updated the pull request to adjust for the appIconIndicators refactoring. @micheleg can you let me know if you'd ever accept this change? or there's work you want me to do to it before you'd accept it?

**Comment by franglais125** [comment]
@philipl While I can't speak for @micheleg , on my side I ran out of time in the last few months and couldn't test your branch more thoroughly. I hope I'll get back to it some day, as it's pretty neat (and something I remember from Unity as well).

If it's any indication, it took me ~6 months to get the multi-monitor branch merged.  But it was nicely done eventually, with some nice rework by Michele.

**Comment by franglais125** [comment]
Just an idea: would it be possible to add some configurability?

1. I'm sure some users won't want this at all.

2. Perhaps make the trash configurable as well?

Something like:


screenshot from 2018-01-07 20-08-47

**Comment by philipl** [comment]
Done!

**Comment by franglais125** [comment]
Gorgeous, thanks! For anyone reading, here is a screenshot of the prefs:

screenshot from 2018-01-08 23-41-13

**Comment by micheleg** [comment]
Hi,

sorry for the late reply.  Thanks for your work. I quickly tested your code a week ago and I was going to ask for some settings but I see that it has been done now. I still find it a bit incomplete ( without drag and drop support, yet the changes seems decently self-container so I'm keen on trying to merge this. 

Can you please summarize if there's any known corner case or issue? I didn't notice anything wrong on my side.  I'll now  try to look more thoroughly at your code.

**Comment by philipl** [comment]
The issues I'm aware of:
- No drag and drop for trash. I think the best thing to do here is let the gnome shell folks implement this for [their desktop icons extension](https://gitlab.gnome.org/csoriano/org.gnome.desktop-icons) and then copy/use it. :-)
- No support for window tracking with Wayland. This requires the Ubuntu team to extend the window tracking system to work with Wayland. Without it, Nautilus windows for trash/devices cannot be associated with the icons
- Trash icon cannot be pinned to the bottom of the bar as in Unity. This would probably be easier for you, but I really struggled to understand the St layout code.

Thanks for merging!

**Comment by franglais125** [comment]
It seems this was un-merged...

Perhaps a local `push -f` before pulling, or simply wrongly merged?

**Comment by philipl** [comment]
Yeah, there was a force push reported and now it's not on master.

**Comment by micheleg** [comment]
Yes, my fault, I pushed your branch by mistake while merging another patch. Sorry for the confusion.

**Comment by philipl** [comment]
Can you reopen this pull request then? It won't let me do it.

**Pull request merged**
